// <auto-generated />
namespace PassionProject1N01659860.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user));
        
        string IMigrationMetadata.Id
        {
            get { return "202406070010051_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
